
spring:
  datasource:
    name: shop
    url: jdbc:mysql://localhost:3307/shop?serverTimezone=UTC
    username: root
    password: 222222
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
